# Generated by Django 6.0.2 on 2026-03-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
