# Generated by Django 6.0.2 on 2026-03-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rack_nivel_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
