# Generated by Django 6.0.2 on 2026-03-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_seccion_capacidad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nivel',
            unique_together={('rack', 'codigo'), ('rack', 'posicion')},
        ),
    ]
