# Generated by Django 6.0.2 on 2026-04-06 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_userrole_company'),
        ('store', '0005_alter_nivel_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=120)),
                ('contenido', models.CharField(blank=True, max_length=255)),
                ('proveedor', models.CharField(blank=True, max_length=255)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('almacenado', 'Almacenado'), ('en_transito', 'En transito')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets', to='store.almacen')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='companies.company')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets', to='store.nivel')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets', to='store.rack')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets', to='store.seccion')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('company', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recepcion', 'Recepcion'), ('asignacion', 'Asignacion'), ('traslado', 'Traslado'), ('estado', 'Cambio de estado')], max_length=20)),
                ('estado_origen', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('almacenado', 'Almacenado'), ('en_transito', 'En transito')], max_length=20)),
                ('estado_destino', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('almacenado', 'Almacenado'), ('en_transito', 'En transito')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_pallet', to='store.almacen')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_pallet', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_pallet', to='store.nivel')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_pallet', to='store.rack')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_pallet', to='store.seccion')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='store.pallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=40, unique=True)),
                ('registro_recepcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='store.pallet')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
