# Generated by Django 6.0.1 on 2026-01-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
