# Generated by Django 6.0.2 on 2026-03-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_userrole_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
